site_name: ckanext-jsoncatalog

pages:
    - Home: index.md
    - Desarrollo: development.md
    - Produccion: production.md

theme: readthedocs
repo_url: https://github.com/JoseSalgado1024/ckanext-jsoncatalog
site_author: Jose A. Salgado

extra:
    version: 1.0
